# Application Configuration
spring:
  application:
    name: edgar-workflow-v2-poc
  main:
    banner-mode: off
  profiles:
    default: dev
    active: dev

# for logging
logging:
  level:
    root: debug
    console:
      level: debug
      
      